import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from '@/shared/theme/ThemeRegistry'
import { theme } from '@/features/app'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeRegistry theme={theme} options={{ key: 'mui' }}>{children}</ThemeRegistry>
      </body>
    </html>
  )
}
